server:
  port: 9001

spring:
  application:
    name: cloud-alibaba-provider
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"