eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/
    instance:
        hostname: eureka7002.com
server:
    port: 7002
