server:
  port: 83

spring:
  application:
    name: cloud-alibaba-consumer
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'